name: PluginCraftGeocaching
main: com.plugincraft.geocaching.GeoCachingPlugin
version: 1.0.0
api-version: 1.20
author: Plugin Craft
commands:
  geocache:
    description: Geocaching main command
    usage: /geocache help
    aliases: [gc, geoc]
permissions:
  geocache.use: {default: true}
  geocache.gps: {default: true}
  geocache.create: {default: op}
  geocache.remove: {default: op}
  geocache.admin: {default: op}
  geocache.hidepack: {default: true}
  geocache.loot: {default: op}
  geocache.leaderboard: {default: true}
  geocache.gui: {default: true}